npcs:
  '0': "Steve"

variables: # Variables are useful for a tons of things, here we use them basically like a config file, where the coords you set below will automatically be the ones used during the quest
  caveLoc: "0;0;0;world" # X;Y;Z;world_name - Location of your Cave
  returnLoc: "0;0;0;world" # X;Y;Z;world_name - Location of your NPC
  batSpawn: "0;0;0;world BAT 5" # X;Y;Z;world_name MOBNAME amount - Spawn Bats location and amount